// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: auction.proto

package auction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User information
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_auction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_auction_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Product information
type ProductInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Seller         string                 `protobuf:"bytes,1,opt,name=seller,proto3" json:"seller,omitempty"`
	Product        string                 `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	InitialPrice   float32                `protobuf:"fixed32,3,opt,name=initial_price,json=initialPrice,proto3" json:"initial_price,omitempty"`
	CurrentPrice   float32                `protobuf:"fixed32,4,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	AuctionEndTime int64                  `protobuf:"varint,5,opt,name=auction_end_time,json=auctionEndTime,proto3" json:"auction_end_time,omitempty"` // Unix timestamp when auction ends
	IsActive       bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`                     // Whether auction is still active
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProductInfo) Reset() {
	*x = ProductInfo{}
	mi := &file_auction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductInfo) ProtoMessage() {}

func (x *ProductInfo) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductInfo.ProtoReflect.Descriptor instead.
func (*ProductInfo) Descriptor() ([]byte, []int) {
	return file_auction_proto_rawDescGZIP(), []int{1}
}

func (x *ProductInfo) GetSeller() string {
	if x != nil {
		return x.Seller
	}
	return ""
}

func (x *ProductInfo) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *ProductInfo) GetInitialPrice() float32 {
	if x != nil {
		return x.InitialPrice
	}
	return 0
}

func (x *ProductInfo) GetCurrentPrice() float32 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *ProductInfo) GetAuctionEndTime() int64 {
	if x != nil {
		return x.AuctionEndTime
	}
	return 0
}

func (x *ProductInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

// Bid information
type BidInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buyer         string                 `protobuf:"bytes,1,opt,name=buyer,proto3" json:"buyer,omitempty"`
	Product       string                 `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	Amount        float32                `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidInfo) Reset() {
	*x = BidInfo{}
	mi := &file_auction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidInfo) ProtoMessage() {}

func (x *BidInfo) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidInfo.ProtoReflect.Descriptor instead.
func (*BidInfo) Descriptor() ([]byte, []int) {
	return file_auction_proto_rawDescGZIP(), []int{2}
}

func (x *BidInfo) GetBuyer() string {
	if x != nil {
		return x.Buyer
	}
	return ""
}

func (x *BidInfo) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *BidInfo) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// Purchased item information
type PurchasedItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       string                 `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	Seller        string                 `protobuf:"bytes,2,opt,name=seller,proto3" json:"seller,omitempty"`
	PurchasePrice float32                `protobuf:"fixed32,3,opt,name=purchase_price,json=purchasePrice,proto3" json:"purchase_price,omitempty"`
	PurchaseTime  int64                  `protobuf:"varint,4,opt,name=purchase_time,json=purchaseTime,proto3" json:"purchase_time,omitempty"` // Unix timestamp when purchased
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurchasedItem) Reset() {
	*x = PurchasedItem{}
	mi := &file_auction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchasedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchasedItem) ProtoMessage() {}

func (x *PurchasedItem) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchasedItem.ProtoReflect.Descriptor instead.
func (*PurchasedItem) Descriptor() ([]byte, []int) {
	return file_auction_proto_rawDescGZIP(), []int{3}
}

func (x *PurchasedItem) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *PurchasedItem) GetSeller() string {
	if x != nil {
		return x.Seller
	}
	return ""
}

func (x *PurchasedItem) GetPurchasePrice() float32 {
	if x != nil {
		return x.PurchasePrice
	}
	return 0
}

func (x *PurchasedItem) GetPurchaseTime() int64 {
	if x != nil {
		return x.PurchaseTime
	}
	return 0
}

// Register user
type RegisterUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserRequest) Reset() {
	*x = RegisterUserRequest{}
	mi := &file_auction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserRequest) ProtoMessage() {}

func (x *RegisterUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserRequest) Descriptor() ([]byte, []int) {
	return file_auction_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RegisterUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserResponse) Reset() {
	*x = RegisterUserResponse{}
	mi := &file_auction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserResponse) ProtoMessage() {}

func (x *RegisterUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterUserResponse) Descriptor() ([]byte, []int) {
	return file_auction_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Add product for sale
type AddProductRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Seller                 string                 `protobuf:"bytes,1,opt,name=seller,proto3" json:"seller,omitempty"`
	Product                string                 `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	InitialPrice           float32                `protobuf:"fixed32,3,opt,name=initial_price,json=initialPrice,proto3" json:"initial_price,omitempty"`
	AuctionDurationSeconds int32                  `protobuf:"varint,4,opt,name=auction_duration_seconds,json=auctionDurationSeconds,proto3" json:"auction_duration_seconds,omitempty"` // How long the auction should run
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AddProductRequest) Reset() {
	*x = AddProductRequest{}
	mi := &file_auction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductRequest) ProtoMessage() {}

func (x *AddProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductRequest.ProtoReflect.Descriptor instead.
func (*AddProductRequest) Descriptor() ([]byte, []int) {
	return file_auction_proto_rawDescGZIP(), []int{6}
}

func (x *AddProductRequest) GetSeller() string {
	if x != nil {
		return x.Seller
	}
	return ""
}

func (x *AddProductRequest) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *AddProductRequest) GetInitialPrice() float32 {
	if x != nil {
		return x.InitialPrice
	}
	return 0
}

func (x *AddProductRequest) GetAuctionDurationSeconds() int32 {
	if x != nil {
		return x.AuctionDurationSeconds
	}
	return 0
}

type AddProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProductResponse) Reset() {
	*x = AddProductResponse{}
	mi := &file_auction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProductResponse) ProtoMessage() {}

func (x *AddProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProductResponse.ProtoReflect.Descriptor instead.
func (*AddProductResponse) Descriptor() ([]byte, []int) {
	return file_auction_proto_rawDescGZIP(), []int{7}
}

func (x *AddProductResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddProductResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Place bid
type PlaceBidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buyer         string                 `protobuf:"bytes,1,opt,name=buyer,proto3" json:"buyer,omitempty"`
	Product       string                 `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	Amount        float32                `protobuf:"fixed32,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceBidRequest) Reset() {
	*x = PlaceBidRequest{}
	mi := &file_auction_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceBidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBidRequest) ProtoMessage() {}

func (x *PlaceBidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBidRequest.ProtoReflect.Descriptor instead.
func (*PlaceBidRequest) Descriptor() ([]byte, []int) {
	return file_auction_proto_rawDescGZIP(), []int{8}
}

func (x *PlaceBidRequest) GetBuyer() string {
	if x != nil {
		return x.Buyer
	}
	return ""
}

func (x *PlaceBidRequest) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

func (x *PlaceBidRequest) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PlaceBidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CurrentPrice  float32                `protobuf:"fixed32,3,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceBidResponse) Reset() {
	*x = PlaceBidResponse{}
	mi := &file_auction_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceBidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBidResponse) ProtoMessage() {}

func (x *PlaceBidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBidResponse.ProtoReflect.Descriptor instead.
func (*PlaceBidResponse) Descriptor() ([]byte, []int) {
	return file_auction_proto_rawDescGZIP(), []int{9}
}

func (x *PlaceBidResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PlaceBidResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PlaceBidResponse) GetCurrentPrice() float32 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

// Get catalog
type GetCatalogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogRequest) Reset() {
	*x = GetCatalogRequest{}
	mi := &file_auction_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogRequest) ProtoMessage() {}

func (x *GetCatalogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogRequest.ProtoReflect.Descriptor instead.
func (*GetCatalogRequest) Descriptor() ([]byte, []int) {
	return file_auction_proto_rawDescGZIP(), []int{10}
}

type GetCatalogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductInfo         `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCatalogResponse) Reset() {
	*x = GetCatalogResponse{}
	mi := &file_auction_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCatalogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCatalogResponse) ProtoMessage() {}

func (x *GetCatalogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCatalogResponse.ProtoReflect.Descriptor instead.
func (*GetCatalogResponse) Descriptor() ([]byte, []int) {
	return file_auction_proto_rawDescGZIP(), []int{11}
}

func (x *GetCatalogResponse) GetProducts() []*ProductInfo {
	if x != nil {
		return x.Products
	}
	return nil
}

// Get product details
type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       string                 `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_auction_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_auction_proto_rawDescGZIP(), []int{12}
}

func (x *GetProductRequest) GetProduct() string {
	if x != nil {
		return x.Product
	}
	return ""
}

type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Product       *ProductInfo           `protobuf:"bytes,2,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_auction_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_auction_proto_rawDescGZIP(), []int{13}
}

func (x *GetProductResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetProductResponse) GetProduct() *ProductInfo {
	if x != nil {
		return x.Product
	}
	return nil
}

// Get purchased items for a user
type GetPurchasedItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buyer         string                 `protobuf:"bytes,1,opt,name=buyer,proto3" json:"buyer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPurchasedItemsRequest) Reset() {
	*x = GetPurchasedItemsRequest{}
	mi := &file_auction_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPurchasedItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPurchasedItemsRequest) ProtoMessage() {}

func (x *GetPurchasedItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPurchasedItemsRequest.ProtoReflect.Descriptor instead.
func (*GetPurchasedItemsRequest) Descriptor() ([]byte, []int) {
	return file_auction_proto_rawDescGZIP(), []int{14}
}

func (x *GetPurchasedItemsRequest) GetBuyer() string {
	if x != nil {
		return x.Buyer
	}
	return ""
}

type GetPurchasedItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*PurchasedItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPurchasedItemsResponse) Reset() {
	*x = GetPurchasedItemsResponse{}
	mi := &file_auction_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPurchasedItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPurchasedItemsResponse) ProtoMessage() {}

func (x *GetPurchasedItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auction_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPurchasedItemsResponse.ProtoReflect.Descriptor instead.
func (*GetPurchasedItemsResponse) Descriptor() ([]byte, []int) {
	return file_auction_proto_rawDescGZIP(), []int{15}
}

func (x *GetPurchasedItemsResponse) GetItems() []*PurchasedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_auction_proto protoreflect.FileDescriptor

const file_auction_proto_rawDesc = "" +
	"\n" +
	"\rauction.proto\x12\aauction\"\x1a\n" +
	"\x04User\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xd0\x01\n" +
	"\vProductInfo\x12\x16\n" +
	"\x06seller\x18\x01 \x01(\tR\x06seller\x12\x18\n" +
	"\aproduct\x18\x02 \x01(\tR\aproduct\x12#\n" +
	"\rinitial_price\x18\x03 \x01(\x02R\finitialPrice\x12#\n" +
	"\rcurrent_price\x18\x04 \x01(\x02R\fcurrentPrice\x12(\n" +
	"\x10auction_end_time\x18\x05 \x01(\x03R\x0eauctionEndTime\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\"Q\n" +
	"\aBidInfo\x12\x14\n" +
	"\x05buyer\x18\x01 \x01(\tR\x05buyer\x12\x18\n" +
	"\aproduct\x18\x02 \x01(\tR\aproduct\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x02R\x06amount\"\x8d\x01\n" +
	"\rPurchasedItem\x12\x18\n" +
	"\aproduct\x18\x01 \x01(\tR\aproduct\x12\x16\n" +
	"\x06seller\x18\x02 \x01(\tR\x06seller\x12%\n" +
	"\x0epurchase_price\x18\x03 \x01(\x02R\rpurchasePrice\x12#\n" +
	"\rpurchase_time\x18\x04 \x01(\x03R\fpurchaseTime\")\n" +
	"\x13RegisterUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"J\n" +
	"\x14RegisterUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa4\x01\n" +
	"\x11AddProductRequest\x12\x16\n" +
	"\x06seller\x18\x01 \x01(\tR\x06seller\x12\x18\n" +
	"\aproduct\x18\x02 \x01(\tR\aproduct\x12#\n" +
	"\rinitial_price\x18\x03 \x01(\x02R\finitialPrice\x128\n" +
	"\x18auction_duration_seconds\x18\x04 \x01(\x05R\x16auctionDurationSeconds\"H\n" +
	"\x12AddProductResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"Y\n" +
	"\x0fPlaceBidRequest\x12\x14\n" +
	"\x05buyer\x18\x01 \x01(\tR\x05buyer\x12\x18\n" +
	"\aproduct\x18\x02 \x01(\tR\aproduct\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x02R\x06amount\"k\n" +
	"\x10PlaceBidResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rcurrent_price\x18\x03 \x01(\x02R\fcurrentPrice\"\x13\n" +
	"\x11GetCatalogRequest\"F\n" +
	"\x12GetCatalogResponse\x120\n" +
	"\bproducts\x18\x01 \x03(\v2\x14.auction.ProductInfoR\bproducts\"-\n" +
	"\x11GetProductRequest\x12\x18\n" +
	"\aproduct\x18\x01 \x01(\tR\aproduct\"Z\n" +
	"\x12GetProductResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12.\n" +
	"\aproduct\x18\x02 \x01(\v2\x14.auction.ProductInfoR\aproduct\"0\n" +
	"\x18GetPurchasedItemsRequest\x12\x14\n" +
	"\x05buyer\x18\x01 \x01(\tR\x05buyer\"I\n" +
	"\x19GetPurchasedItemsResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.auction.PurchasedItemR\x05items2\xcf\x03\n" +
	"\x0eAuctionService\x12K\n" +
	"\fRegisterUser\x12\x1c.auction.RegisterUserRequest\x1a\x1d.auction.RegisterUserResponse\x12E\n" +
	"\n" +
	"AddProduct\x12\x1a.auction.AddProductRequest\x1a\x1b.auction.AddProductResponse\x12?\n" +
	"\bPlaceBid\x12\x18.auction.PlaceBidRequest\x1a\x19.auction.PlaceBidResponse\x12E\n" +
	"\n" +
	"GetCatalog\x12\x1a.auction.GetCatalogRequest\x1a\x1b.auction.GetCatalogResponse\x12E\n" +
	"\n" +
	"GetProduct\x12\x1a.auction.GetProductRequest\x1a\x1b.auction.GetProductResponse\x12Z\n" +
	"\x11GetPurchasedItems\x12!.auction.GetPurchasedItemsRequest\x1a\".auction.GetPurchasedItemsResponseB6Z4github.com/930r91na/Subasta-grpc/pkg/auction;auctionb\x06proto3"

var (
	file_auction_proto_rawDescOnce sync.Once
	file_auction_proto_rawDescData []byte
)

func file_auction_proto_rawDescGZIP() []byte {
	file_auction_proto_rawDescOnce.Do(func() {
		file_auction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auction_proto_rawDesc), len(file_auction_proto_rawDesc)))
	})
	return file_auction_proto_rawDescData
}

var file_auction_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_auction_proto_goTypes = []any{
	(*User)(nil),                      // 0: auction.User
	(*ProductInfo)(nil),               // 1: auction.ProductInfo
	(*BidInfo)(nil),                   // 2: auction.BidInfo
	(*PurchasedItem)(nil),             // 3: auction.PurchasedItem
	(*RegisterUserRequest)(nil),       // 4: auction.RegisterUserRequest
	(*RegisterUserResponse)(nil),      // 5: auction.RegisterUserResponse
	(*AddProductRequest)(nil),         // 6: auction.AddProductRequest
	(*AddProductResponse)(nil),        // 7: auction.AddProductResponse
	(*PlaceBidRequest)(nil),           // 8: auction.PlaceBidRequest
	(*PlaceBidResponse)(nil),          // 9: auction.PlaceBidResponse
	(*GetCatalogRequest)(nil),         // 10: auction.GetCatalogRequest
	(*GetCatalogResponse)(nil),        // 11: auction.GetCatalogResponse
	(*GetProductRequest)(nil),         // 12: auction.GetProductRequest
	(*GetProductResponse)(nil),        // 13: auction.GetProductResponse
	(*GetPurchasedItemsRequest)(nil),  // 14: auction.GetPurchasedItemsRequest
	(*GetPurchasedItemsResponse)(nil), // 15: auction.GetPurchasedItemsResponse
}
var file_auction_proto_depIdxs = []int32{
	1,  // 0: auction.GetCatalogResponse.products:type_name -> auction.ProductInfo
	1,  // 1: auction.GetProductResponse.product:type_name -> auction.ProductInfo
	3,  // 2: auction.GetPurchasedItemsResponse.items:type_name -> auction.PurchasedItem
	4,  // 3: auction.AuctionService.RegisterUser:input_type -> auction.RegisterUserRequest
	6,  // 4: auction.AuctionService.AddProduct:input_type -> auction.AddProductRequest
	8,  // 5: auction.AuctionService.PlaceBid:input_type -> auction.PlaceBidRequest
	10, // 6: auction.AuctionService.GetCatalog:input_type -> auction.GetCatalogRequest
	12, // 7: auction.AuctionService.GetProduct:input_type -> auction.GetProductRequest
	14, // 8: auction.AuctionService.GetPurchasedItems:input_type -> auction.GetPurchasedItemsRequest
	5,  // 9: auction.AuctionService.RegisterUser:output_type -> auction.RegisterUserResponse
	7,  // 10: auction.AuctionService.AddProduct:output_type -> auction.AddProductResponse
	9,  // 11: auction.AuctionService.PlaceBid:output_type -> auction.PlaceBidResponse
	11, // 12: auction.AuctionService.GetCatalog:output_type -> auction.GetCatalogResponse
	13, // 13: auction.AuctionService.GetProduct:output_type -> auction.GetProductResponse
	15, // 14: auction.AuctionService.GetPurchasedItems:output_type -> auction.GetPurchasedItemsResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_auction_proto_init() }
func file_auction_proto_init() {
	if File_auction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auction_proto_rawDesc), len(file_auction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auction_proto_goTypes,
		DependencyIndexes: file_auction_proto_depIdxs,
		MessageInfos:      file_auction_proto_msgTypes,
	}.Build()
	File_auction_proto = out.File
	file_auction_proto_goTypes = nil
	file_auction_proto_depIdxs = nil
}
